problems with enabled INPUT_SHAPING and stuck boot, switching to bugfix

diff --git a/buildroot/bin/build_example b/buildroot/bin/build_example
--- a/buildroot/bin/build_example
+++ b/buildroot/bin/build_example
@@ -5,9 +5,7 @@
 # Usage: build_example internal config-home config-folder
 #
 
-HERE=`dirname $0`
-
-. "$HERE/mfutil"
+. mfutil
 
 # Require 'internal' as the first argument
 [[ "$1" == "internal" ]] || { echo "Don't call this script directly, use build_all_examples instead." ; exit 1 ; }
@@ -38,6 +36,6 @@ unset IFS; set +f
 echo -e "\n#define NO_CONTROLLER_CUSTOM_WIRING_WARNING" >> Marlin/Configuration.h
 
 echo "Building the firmware now..."
-"$HERE/mftest" -s -a -n1 || { echo "Failed"; exit 1; }
+$HERE/mftest -s -a -n1 || { echo "Failed"; exit 1; }
 
 echo "Success"
